In [10]:
!pip install torch

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 1.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 60.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 48.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 36.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 6.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 13.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 8.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 4.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 75.7 MB/s eta 0:00:00
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlin

##Model Config

In [1]:
from transformers import BertConfig, BertModel

# Building the config
config = BertConfig()

# Building the model from the config
model = BertModel(config)

In [2]:
print(config)

BertConfig {
  "_attn_implementation_autoset": true,
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.47.1",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}



In [3]:
from transformers import BertModel

model1 = BertModel.from_pretrained("bert-base-cased")

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/436M [00:00<?, ?B/s]

In [6]:
model.save_pretrained("/content/drive/MyDrive/CollabData/saved_model")

###Transformer for Inference

In [8]:
sequences = ["Hello!", "Cool.", "Nice!"]

In [12]:
encoded_sequences = [
    [101, 7592, 999, 102],
    [101, 4658, 1012, 102],
    [101, 3835, 999, 102],
]

In [13]:
import torch

model_inputs = torch.tensor(encoded_sequences)

In [14]:
output = model(model_inputs)

In [15]:
print(output)

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[-2.1899e-01,  3.4928e-01, -1.0855e+00,  ...,  2.7666e+00,
           1.3274e-01,  8.1649e-01],
         [ 3.4197e-01,  2.0728e-01,  2.7512e-01,  ...,  2.2574e+00,
          -1.6604e+00,  8.1931e-01],
         [-2.0295e-01, -6.6834e-01,  2.2918e-02,  ...,  1.6748e+00,
           5.1223e-01,  1.3547e-01],
         [ 3.6200e-02,  1.6215e-01, -1.0105e+00,  ...,  2.6845e+00,
          -3.9305e-01, -1.9301e-01]],

        [[-7.8524e-01,  1.1852e+00, -1.9951e-02,  ...,  1.8727e+00,
          -6.6347e-01,  1.4719e+00],
         [-1.1270e-01,  1.5862e+00,  4.3407e-01,  ...,  1.9690e+00,
          -5.3938e-01,  7.1603e-01],
         [-4.5540e-01,  6.3417e-01,  5.2937e-01,  ...,  1.7325e+00,
          -1.9104e-01,  4.8381e-01],
         [-9.7341e-01,  6.9752e-01,  5.3963e-01,  ...,  3.1721e+00,
          -6.2046e-02,  1.0509e+00]],

        [[ 3.0333e-03,  9.5359e-01,  3.6743e-02,  ...,  2.4025e+00,
           5.5823e-01,  1

##Tokenizers

###Word-Based Tokenizers

In [18]:
tokenized_text = "Jim Henson was a puppeteer".split()
print(tokenized_text)

['Jim', 'Henson', 'was', 'a', 'puppeteer']


###Character-Based Tokenizers

###Subword Tokenizations

###Other Type

- Byte-level BPE, as used in GPT-2
- WordPiece, as used in BERT
- SentencePiece or Unigram, as used in several multilingual models

##Loading and Saving System

In [19]:
from transformers import BertTokenizer

tokenizer = BertTokenizer.from_pretrained("bert-base-cased")

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

In [20]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")

In [21]:
tokenizer("Using a Transformer network is simple")

{'input_ids': [101, 7993, 170, 13809, 23763, 2443, 1110, 3014, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [22]:
tokenizer.save_pretrained("/content/drive/MyDrive/CollabData/saved_tokenizers")

('/content/drive/MyDrive/CollabData/saved_tokenizers/tokenizer_config.json',
 '/content/drive/MyDrive/CollabData/saved_tokenizers/special_tokens_map.json',
 '/content/drive/MyDrive/CollabData/saved_tokenizers/vocab.txt',
 '/content/drive/MyDrive/CollabData/saved_tokenizers/added_tokens.json',
 '/content/drive/MyDrive/CollabData/saved_tokenizers/tokenizer.json')

##Encoding

###Tokenization

In [25]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")

sequence = "Using a Transformer network is simple"
sequences = "We need to improve the Accuracy by adding more sample"
tokens = tokenizer.tokenize(sequence)
token = tokenizer.tokenize(sequences)

print(tokens)
print(token)

['Using', 'a', 'Trans', '##former', 'network', 'is', 'simple']
['We', 'need', 'to', 'improve', 'the', 'A', '##cc', '##ura', '##cy', 'by', 'adding', 'more', 'sample']


####From tokens to input IDs

In [28]:
ids = tokenizer.convert_tokens_to_ids(tokens)
id = tokenizer.convert_tokens_to_ids(token)

print(ids)
print(id)

[7993, 170, 13809, 23763, 2443, 1110, 3014]
[1284, 1444, 1106, 4607, 1103, 138, 19515, 4084, 3457, 1118, 5321, 1167, 6876]


###Decoding

In [29]:
decoded_string = tokenizer.decode([7993, 170, 11303, 1200, 2443, 1110, 3014])
decoded_strings = tokenizer.decode([1284, 1444, 1106, 4607, 1103, 138, 19515, 4084, 3457, 1118, 5321, 1167, 6876])
print(decoded_string)
print(decoded_strings)

Using a transformer network is simple
We need to improve the Accuracy by adding more sample


##Multiple-Sequences

In [32]:
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

sequence = "I've been waiting for this course my whole life."

tokens = tokenizer.tokenize(sequence)
ids = tokenizer.convert_tokens_to_ids(tokens)
input_ids = torch.tensor(ids)
# This line will fail.
model(input_ids)

IndexError: too many indices for tensor of dimension 1

In [31]:
tokenized_inputs = tokenizer(sequence, return_tensors="pt")
print(tokenized_inputs["input_ids"])

tensor([[  101,  1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,
          2607,  2026,  2878,  2166,  1012,   102]])


In [36]:
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

sequence = "I've been waiting for this course my whole life."
sequences = "This course is amazing!"

tokens = tokenizer.tokenize(sequence)
token = tokenizer.tokenize(sequences)
ids = tokenizer.convert_tokens_to_ids(tokens)
id = tokenizer.convert_tokens_to_ids(token)

input_ids = torch.tensor([ids])
input_id = torch.tensor([id])
print("Input IDs:", input_ids)
print("Input IDs:", input_id)

output = model(input_ids) #LOC
outputs = model(input_id) #LOC
print("Logits:", output.logits)
print("Logits:", outputs.logits)

Input IDs: tensor([[1045, 1005, 2310, 2042, 3403, 2005, 2023, 2607, 2026, 2878, 2166, 1012]])
Input IDs: tensor([[2023, 2607, 2003, 6429,  999]])
Logits: tensor([[-2.7220,  2.7847]], grad_fn=<AddmmBackward0>)
Logits: tensor([[-4.2425,  4.6362]], grad_fn=<AddmmBackward0>)


In [34]:
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

sequence1_ids = [[200, 200, 200]]
sequence2_ids = [[200, 200]]
batched_ids = [
    [200, 200, 200],
    [200, 200, tokenizer.pad_token_id],
]

print(model(torch.tensor(sequence1_ids)).logits)
print(model(torch.tensor(sequence2_ids)).logits)
print(model(torch.tensor(batched_ids)).logits)

We strongly recommend passing in an `attention_mask` since your input_ids may be padded. See https://huggingface.co/docs/transformers/troubleshooting#incorrect-output-when-padding-tokens-arent-masked.


tensor([[ 1.5694, -1.3895]], grad_fn=<AddmmBackward0>)
tensor([[ 0.5803, -0.4125]], grad_fn=<AddmmBackward0>)
tensor([[ 1.5694, -1.3895],
        [ 1.3374, -1.2163]], grad_fn=<AddmmBackward0>)


##Attention-Mask

In [38]:
batched_ids = [
    [200, 200, 200],
    [200, 200, tokenizer.pad_token_id],
]

attention_mask = [
    [1, 1, 1],
    [1, 1, 0],
]

outputs = model(torch.tensor(batched_ids), attention_mask=torch.tensor(attention_mask))
print(outputs.logits)

tensor([[ 1.5694, -1.3895],
        [ 0.5803, -0.4125]], grad_fn=<AddmmBackward0>)
